### ISSUE TITLE
Some parts of the map are not loading

### ISSUE THREAD

**Issue by cangunes** [GeyserMC/GeyserWiki#113] opened 2023-01-10 19:51 UTC
Some parts of the map are not loading, what can i do in this problem.

![image](https://user-images.githubusercontent.com/107223612/211648613-304ee443-a7d5-4a22-8349-6b8eea9237f5.png)

**Comment by Kas-tle** [comment] 2023-01-10 19:54
1. Likely a duplicate of https://github.com/GeyserMC/Geyser/issues/3490
2. This is the repository for Geyser's wiki, not the program itself
3. See https://github.com/GeyserMC/Geyser/issues/3499#issuecomment-1376870315 for what you can do currently to resolve it

**Comment by Jens-Co** [comment] 2023-01-10 20:38
Like Kastle said. This is the wrong repository.

Correct repo; https://github.com/GeyserMC/Geyser/issues/new/choose

Also if you create issues provide us as much details as possible. GeyserDump , Server logs / details + replication steps (not needed in this case).

**Closed by Jens-Co** 2023-01-10 20:38 UTC
