### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by npmnishantsharma** [GeyserMC/GeyserWiki#205] opened 2023-09-25 14:20 UTC
Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b69-492be77) (Is it up to date?)
--
243 | java.lang.ExceptionInInitializerError: null
244 | at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[floodgate-spigot.jar:?]
245 | at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[floodgate-spigot.jar:?]
246 | at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[floodgate-spigot.jar:?]
247 | at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[floodgate-spigot.jar:?]
248 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
249 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-201]
250 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-201]
251 | at org.bukkit.plugin.SimplePluginManager

**Comment by onebeastchris** [comment] 2023-09-25 14:34
Duplicate of https://github.com/GeyserMC/Floodgate/issues/451 - see there for the fix.
In the future, please open an issue on the appropriate GitHub repo - e.g. Geyser issues in the GeyserMC/Geyser repository, and Floodgate one's in GeyserMC/Floodgate.

**Closed by onebeastchris** 2023-09-25 14:34 UTC
